ARG NODE_VERSION=22
FROM node:${NODE_VERSION}-alpine
RUN apk add --no-cache git
WORKDIR /app
COPY package.json package-lock.json .npmrc ./
RUN npm ci --allow-git=all
COPY . .
RUN npm run build
CMD ["npm", "run", "test"]
