#!/usr/bin/env node
/**
 * Reports exports that nothing references.
 *
 * An export is reachable when the package entry points publish it or another
 * module imports it. Anything else is unreachable code that `noUnusedLocals`
 * cannot see: `export` alone makes a declaration "used" as far as tsc is
 * concerned, which is how ~400 lines of dead code accumulated here.
 *
 * Only meaningful because src/index.ts lists its exports explicitly; with
 * `export *` every internal helper counted as published. CI invokes this as part
 * of `npm run lint`.
 */

import { readFileSync, readdirSync, statSync } from 'node:fs';
import path from 'node:path';

/** Files whose exports are the package's public surface. */
const ENTRY_POINTS = ['src/index.ts', 'src/cli.ts', 'src/external/insight-provider.ts'];

/** Generated by other tools; their shape is not ours to trim. */
const GENERATED = 'src/generated/';

function collect(dir, files = []) {
  for (const entry of readdirSync(dir)) {
    const full = path.join(dir, entry);
    if (statSync(full).isDirectory()) collect(full, files);
    else if (full.endsWith('.ts')) files.push(full);
  }
  return files;
}

/**
 * Source with template literals blanked out.
 *
 * The starter templates embed TypeScript, so `export function sendError` inside
 * a template string is not a declaration of this package.
 */
function withoutTemplateLiterals(source) {
  return source.replace(/`(?:[^`\\]|\\[\s\S])*`/g, '``');
}

const sources = new Map(
  [...collect('src'), ...collect('tests')].map((file) => [file, readFileSync(file, 'utf-8')]),
);

const findings = [];

for (const [file, raw] of sources) {
  if (!file.startsWith('src/') || file.startsWith(GENERATED)) continue;
  if (ENTRY_POINTS.includes(file)) continue;

  const source = withoutTemplateLiterals(raw);
  const declarations = [
    ...source.matchAll(/^export\s+(?:async\s+)?(?:function|const|class|interface|type|enum)\s+([A-Za-z0-9_]+)/gm),
  ];

  for (const [, name] of declarations) {
    const referenced = [...sources].some(
      ([other, otherSource]) =>
        other !== file && new RegExp(`\\b${name}\\b`).test(withoutTemplateLiterals(otherSource)),
    );
    if (!referenced) findings.push(`${file}: ${name}`);
  }
}

if (findings.length > 0) {
  console.error(findings.join('\n'));
  console.error(
    `\n${findings.length} export(s) nothing references. Delete them, or drop the export keyword if only their own module needs them.`,
  );
  process.exit(1);
}

console.log('No unreferenced exports.');
