/**
 * Dependency Generator
 *
 * Validates x-micro-contracts-depend-on declarations against config.
 * The deps/ re-export files themselves are generated by the generator
 * (generateDepsReExports), which is the only place that knows the resolved
 * output directories of every module.
 */

/**
 * Validate that config dependsOn is subset of OpenAPI x-micro-contracts-depend-on
 */
export function validateDependsOn(
  openApiDeps: string[],
  configDeps: string[],
  moduleName: string
): { valid: boolean; errors: string[] } {
  const errors: string[] = [];

  for (const dep of configDeps) {
    if (!openApiDeps.includes(dep)) {
      errors.push(
        `${moduleName}.dependsOn includes '${dep}' ` +
        `but it's not declared in OpenAPI x-micro-contracts-depend-on`
      );
    }
  }

  return {
    valid: errors.length === 0,
    errors,
  };
}
